name: Deploy para S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload para S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Upload de arquivos para o S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          aws s3 sync site/ s3://andresantos.click --delete
